name: Deploy Website

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Zugang zum Server
      uses: appleboy/ssh-action@master
      with:
        host: 83.150.28.243
        username: root
        key: ${{ secrets.SSH_KEY}}
        script: |
          cd /var/www/pi-server-website/
          git pull origin main
          sudo systemctl restart nginx
