name: Security Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  security_scan:
    runs-on: ubuntu-latest

    steps:
      # Schritt 1: Checkout des Codes
      - name: Checkout Code
        uses: actions/checkout@v3

      # Schritt 2: Führe Sicherheitsüberprüfung mit OWASP Dependency-Check durch
      - name: Run OWASP Dependency-Check
        run: |
          npx owasp-dependency-check

      # Schritt 3: Bandit für Python-Code-Überprüfung (Falls Python verwendet wird)
      - name: Run Bandit security check (Python)
        run: |
          bandit -r . -f json -o bandit-report.json || true
          cat bandit-report.json
        continue-on-error: true

      # Schritt 4: Installiere ClamAV (Virus-Scanner) und führe einen Scan durch
      - name: Stop any existing clamav processes
        run: |
          sudo pkill freshclam || true
          sudo pkill clamav || true

      - name: Clean up ClamAV log file
        run: |
          sudo rm -f /var/log/clamav/freshclam.log || true
          sudo chown -R clamav:clamav /var/log/clamav
          sudo chmod -R 755 /var/log/clamav

      - name: Install ClamAV
        run: |
          sudo apt-get update
          sudo apt-get install clamav clamav-freshclam libclamav9 libtfm1

      - name: Update ClamAV virus database
        run: |
          sudo freshclam || true  # Ignoriere Fehler, um fortzufahren

      - name: Run ClamAV scan
        run: |
          sudo clamscan -r /path/to/your/server/ || true

      # Schritt 5: Überprüfe offene Ports und SSH-Konfiguration
      - name: Check open ports (using netstat)
        run: |
          sudo apt-get install net-tools
          sudo netstat -tuln

      - name: Check SSH configuration
        run: |
          sudo cat /etc/ssh/sshd_config | grep -E 'PermitRootLogin|PasswordAuthentication|PubkeyAuthentication'

      # Schritt 6: Überprüfe Server-Konfiguration auf Sicherheitsprobleme
      - name: Check server config for security issues
        run: |
          sudo lynis audit system
